### ISSUE TITLE
Inference with MuLaN

### ISSUE THREAD

**Issue by ukemamaster** [lucidrains/musiclm-pytorch#16]
@lucidrains Somehow i got the `MuLaN` trained with the [MusicCaps](https://www.kaggle.com/datasets/googleai/musiccaps) dataset. Now i want to check how close the `text` and `wav` embeddings are. So while extracting `text` and `wav` embeddings using: 
```python
audio_transformer = AudioSpectrogramTransformer(
    dim = 512,
    depth = 6,
    heads = 8,
    dim_head = 64,
    spec_n_fft = 128,
    spec_win_length = 24,
    spec_aug_stretch_factor = 0.8
)

text_transformer = TextTransformer(
    dim = 512,
    depth = 6,
    heads = 8,
    dim_head = 64,
    max_seq_len = 512
)

mulan = MuLaN(
    audio_transformer = audio_transformer,
    text_transformer = text_transformer
)

mulan.to(device)

model = torch.load('results/mulan.45000.pt')

# create new OrderedDict that does not contain `module.`
from collections import OrderedDict
new_state_dict = OrderedDict()
for k, v in model.items():
    name = k[7:] # remove `module.`
    new_state_dict[name] = v

mulan.load_state_dict(new_state_dict)

wavs = torch.randn(2, 1024)
texts = torch.randint(0, 20000, (2, 256))

wav_emb = mulan.get_audio_latents(wavs) 
text_emb = mulan.get_text_latents(texts)

```

I get the following error: 

```python
Traceback (most recent call last):
  File "test_mulan.py", line 140, in <module>
    audio_emb = mulan.get_audio_latents(wavs)
  File "venv/lib/python3.8/site-packages/musiclm_pytorch/musiclm_pytorch.py", line 502, in get_audio_latents
    audio_embeds = self.audio(wavs)
  File "/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/venv/lib/python3.8/site-packages/musiclm_pytorch/musiclm_pytorch.py", line 379, in forward
    x = self.transformer(x, rel_pos_bias = rel_pos_bias)
  File "/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/venv/lib/python3.8/site-packages/musiclm_pytorch/musiclm_pytorch.py", line 217, in forward
    x = attn(x, rel_pos_bias = rel_pos_bias, mask = mask) + x
  File "/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/venv/lib/python3.8/site-packages/musiclm_pytorch/musiclm_pytorch.py", line 163, in forward
    sim = sim + rel_pos_bias
RuntimeError: The size of tensor a (20) must match the size of tensor b (2560) at non-singleton dimension 3

```

It happens only for audio inputs. Not for text.

**Comment by lucidrains** [comment]
@ukemamaster hmm, it runs for me

what version of the library are you on? can you get a script that reproduces the error without all your state dict loading logic?

also, you can do `mulan(wavs, texts, return_similarities = True)` to get the distance between modalities in the joint embedding space

**Comment by lucidrains** [comment]
@ukemamaster you won't get very far with just 5k samples from musiccaps. you need millions...

**Comment by ukemamaster** [comment]
@lucidrains I am using version 0.0.22. Here is a script which can reproduce the bug: 

```python
import torch
from musiclm_pytorch import MusicLM, MuLaNTrainer
from musiclm_pytorch import MuLaN, AudioSpectrogramTransformer, TextTransformer, MuLaNEmbedQuantizer

import random
import numpy as np

device = 'cuda'


audio_transformer = AudioSpectrogramTransformer(
    dim = 512,
    depth = 6,
    heads = 8,
    dim_head = 64,
    spec_n_fft = 128,
    spec_win_length = 24,
    spec_aug_stretch_factor = 0.8
)

text_transformer = TextTransformer(
    dim = 512,
    depth = 6,
    heads = 8,
    dim_head = 64,
    max_seq_len = 512
)

mulan = MuLaN(
    audio_transformer = audio_transformer,
    text_transformer = text_transformer
)

mulan.to(device)
mulan.eval()

wavs = torch.randn(1, 1024).to(device)
texts = torch.randint(0, 20000, (1, 512)).to(device)
#print(wavs.shape, texts.shape)

with torch.no_grad():
     #audio_emb = mulan.get_audio_latents(wavs)
     #text_emb = mulan.get_text_latents(texts)

     score = mulan(wavs, texts, return_similarities = True)
     print(score)


```

Yes i am aware of the fact that 5.5k samples are very few. But first i want to make sure everything works correctly. And then i will add more data. 

I have already talked with Mariana. She recommended me some datasets, that are my next task.

**Comment by lucidrains** [comment]
@ukemamaster ah ok! you are doing things correctly then! i apologize but there was a bug with how i grabbed the dimensions for generating the relative positional encodings

you may have to quickly retrain on your musiccap dataset

thank you for raising this issue!

**Comment by lucidrains** [comment]
@ukemamaster i will be also getting more of the audio stuff solidified over at [open-clip](https://github.com/mlfoundations/open_clip) this week

**Comment by ukemamaster** [comment]
Solved. Thanks

**Comment by jaideep2** [comment]
@ukemamaster can you comment on how you trained text and wav from MusicCaps?

**Comment by ukemamaster** [comment]
@jaideep2 I started as mentioned [here](https://github.com/lucidrains/musiclm-pytorch/issues/9#issuecomment-1421186544). In the `MockTextAudioDataset()` class you should load the wav files and their text description.

**Comment by jaideep2** [comment]
@ukemamaster 
My dataset looks like this
```
Dataset({
    features: ['ytid', 'start_s', 'end_s', 'audioset_positive_labels', 'aspect_list', 'caption', 'author_id', 'is_balanced_subset', 'is_audioset_eval', 'audio', 'download_status'],
    num_rows: 5485
})
```
So I changed the code like this 
```
class MockTextAudioDataset(Dataset):
    def __init__(self, length = 5485, audio_length = 320 * 32):
        super().__init__()
        self.audio_length = audio_length
        self.len = length

    def __len__(self):
        return self.len

    def __getitem__(self, idx):
        wav = self['audio']
        text = self['caption']
        return wav, text
```
but it throws an error
```
training with dataset of 5210 samples and validating with randomly splitted 275 samples

---------------------------------------------------------------------------
RecursionError                            Traceback (most recent call last)
Cell In[15], line 26
     18         return wav, text
     20 trainer = MuLaNTrainer(
     21     mulan = mulan,
     22     dataset = MockTextAudioDataset(),
     23     batch_size = 4
     24 )
---> 26 trainer.train()
RecursionError: maximum recursion depth exceeded
```
What should I change? Its the MusicCaps dataset I got using **load_dataset('google/MusicCaps', split='train')**
